import java.util.*;

import Calculadora.Calculadora;
import Calculadora.TestCalc;

public class App {
    public static void main(String[] args) throws Exception {
       TestCalc test = new TestCalc();
       
       test.firstSum();
       
       System.out.println("-----------------------------------**------------------------");
       test.secondSum();
       
       System.out.println("-----------------------------------**------------------------");
       test.thirdSum();
       
       System.out.println("-----------------------------------**------------------------");
       test.fourthSum();
       
       System.out.println("-----------------------------------**------------------------");
       test.fifthSum();
       
       System.out.println("-----------------------------------**------------------------");
       test.sixthSum();
       
       System.out.println("-----------------------------------**------------------------");
       test.seventhSum();
       
       System.out.println("-----------------------------------**------------------------");
       test.eighthSum();

        System.out.println("-----------------------------------**------------------------");
    }
}
